(define (yang m)
	(mul m 1.02)
)
(define (bank money month)
	(add
		(div money month)
		(mul money 0.00825)
	)
)
(define (cout n tMoney tMonth)
	(if (= n 0)
		tMoney
		(sub 
			(yang (cout (- n 1) tMoney tMonth))
			(bank tMoney tMonth)
		)
	)
)
(setq tMoney 100000)
(setq tMonth 36)
(setq n 36)
(println "贷款" tMoney)
(println "还款总期：" tMonth "个月")
(println "每个月还:" (bank tMoney tMonth))
(println n "个月后还剩:"(cout n tMoney tMonth))
